theme: jekyll-theme-slate

# Site settings
title: Winter is Coming   				  	#你博客的标题
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: a383809663@gmail.com	
description: "雄关漫道真如铁，而今迈步从头越"  			 #网站介绍
keyword: "BY, BY Blog, dayuanshen, hacktonight，Bella" #关键词
url: "https://exileder.github.io"          # 这个就是填写你的博客地址


deploy:
  type: git
  repository: https://github.com/Exileder/exileder.github.io
  branch: master
